### ISSUE TITLE
Create a fancy static website to explain the concept

### ISSUE THREAD

**Issue by evrardjp** [workadventure-suse/workadventure-suse.github.io#1]
We need a static web content to explain the concept.

It can be hosted github pages **until we bring content from other repos, like SUSE specific content or links**

When we'll link SUSE specific content, we'll need to restrict users with login/pass instead of the whole world wide web, and it will be self-hosted.

However it doesn't prevent us to get started.

**Comment by acipm** [comment]
I started making the website with hugo.
The legal notice stub is here: https://github.com/workadventure-suse/workadventure-suse.github.io/blob/main/content/legal.md

If you get the legal notice, you can just add it there, it is markdown-formatted.

**Comment by evrardjp** [comment]
I suppose we can close this now?

**Comment by evrardjp** [comment]
(I misclicked)

**Comment by evrardjp** [comment]
@acipm feel free to close this issue when you think it's done. It will automatically move the card into the right column :)
